### ISSUE TITLE
Sign in with Google not working

### ISSUE THREAD

**Issue by rutson** [browserslist/browserslist-ga#36] opened 2020-06-18 12:57 UTC
`$npx browserslist-ga
npx: installed 83 in 8.976s
Please open this URL in your browser: https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&response_type=code&client_id=343796874716-6k918h5uajk7k3apdua9n8m6her4igv7.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000`

Open URL, log into Google:
![image](https://user-images.githubusercontent.com/14196062/85022619-76256280-b16b-11ea-992a-1eaa53e40016.png)
`Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.`

**Comment by dmfrancisco** [comment] 2020-06-19 11:46
Duplicate of #26.

**Comment by dmfrancisco** [comment] 2020-06-19 11:48
Hey @rutson, you can learn more about this issue and find a workaround [here](https://github.com/browserslist/browserslist-ga/issues/26#issuecomment-568583144). Sorry for the inconvenience.

**Closed by dmfrancisco** 2020-06-19 11:48 UTC
